---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Defines AWS infrastructure used for genreml (OSU CS467 capstone class)"
Resources:
  # Bucket used to host resources used for the production site
  GenremlProdBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: "genreml-cft-model-hosting"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: 'true'
        BlockPublicPolicy: 'true'
        IgnorePublicAcls: 'true'
        RestrictPublicBuckets: 'true'
  # Bucket used to ingest dev model resources
  GenremlIngestionBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: "genreml-cft-model-ingestion"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: 'true'
        BlockPublicPolicy: 'true'
        IgnorePublicAcls: 'true'
        RestrictPublicBuckets: 'true'